version: "3"
services:
  db:
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./appizzas_database:/var/lib/appizzas_database/data
    ports:
      - "3306:3306"
  app:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app
    depends_on:
      - db
    command: yarn start
